main: xnmessentialss.main.Main
name: XNMEssentials
version: 0.8
description: Essential stuff that every Server needs
author: TazeDev
website: https://github.com/TazeDev
commands:
   fly:
      description: &bPlaceholder
   heal:
      description: &bPlaceholder
   vanish:
      description: &bPlaceholder