main: xnmessentialss.main.Main
name: XNMEssentials
version: 0.85
description: Essential stuff that every Server needs
author: TazeDev
website: https://github.com/TazeDev
commands:
   fly:
      description: go wee
   heal:
      description: Heals the player
   vanish:
      description: Vanishes the player
   ad:
      description: Admin Command
   vl:
      description: Shows howmany players are vanished
   troll:
      description: Trollmenu