main: xnmessentialss.main.Main
name: XNMEssentials
version: 0.82
description: Essential stuff that every Server needs
author: TazeDev
website: https://github.com/TazeDev
commands:
   fly:
      description: &bGo wee
   heal:
      description: &bHeals the player
   vanish:
      description: &bVanishes the player
   ad:
      description: &cAdmin command