main: xnmessentialss.main.Main
name: XNMEssentials
version: 0.821
description: Essential stuff that every Server needs
author: TazeDev
website: https://github.com/TazeDev
commands:
   fly:
      description: wee
   heal:
      description: the player
   vanish:
      description: the player
   ad:
      description: commanda